elec <- read.table("/Users/user/Downloads/household_power_consumption.txt", stringsAsFactors = FALSE, header = TRUE, sep = ";")
elec[,1] <- as.Date(elec[,1], format = "%d/%m/%Y")
elec[,1] <- paste(elec[,1], elec[,2])
elec[,1] <- as.POSIXct(elec[,1])
plot(elec[,7]~elec[,1], xlab = "", ylab = "Global active Power (kilowatts)", type = "l")
lines(elec[,8]~elec[,1], col = "Red")
lines(elec[,9]~elec[,1], col = "blue")
legend("topright", legend = c("Sub_metering_1               ", "Sub_metering_2   ", "Sub_metering_3   "), col = c("black", "red", "blue"), lty = 1, lwd = 2, cex = 0.7)
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()